/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMe: typeof import('element-plus/es')['ElSubMe']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpA: typeof import('~icons/ep/a')['default']
    IEpAddDocumentAdd: typeof import('~icons/ep/add-document-add')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpIcon: typeof import('~icons/ep/icon')['default']
    IEpMale: typeof import('~icons/ep/male')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpPotification: typeof import('~icons/ep/potification')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
